### ISSUE TITLE
Library does not compile from the Arduino Cloud IDE for MKR Wi-Fi 1010

### ISSUE THREAD

**Issue by zfields** [arduino-libraries/ArduinoIoTCloud#411] opened 2024-01-30 15:53 UTC
```
/usr/local/bin/arduino-cli compile --fqbn arduino:samd:mkrwifi1010 --build-cache-path /tmp --output-dir /tmp/3214616684/build --build-path /tmp/arduino-build-5FBB2B82E8C1BA32B234A5C999B03F04  /tmp/3214616684/ArduinoIoTCloud_Basic

In file included from /tmp/3214616684/ArduinoIoTCloud_Basic/ArduinoIoTCloud_Basic.ino:18:0:
/tmp/3214616684/ArduinoIoTCloud_Basic/thingProperties.h:3:4: error: #error "Please check Arduino IoT Cloud supported boards list: https://github.com/arduino-libraries/ArduinoIoTCloud/#what"
   #error "Please check Arduino IoT Cloud supported boards list: https://github.com/arduino-libraries/ArduinoIoTCloud/#what"
    ^~~~~

Error during build: exit status 1
```

**Comment by per1234** [comment] 2024-01-31 02:27
Hi @zfields. The cause of the error is caused by the code in the `thingProperties.h` file of your "ArduinoIoTCloud_Basic" sketch, not by the code of the library. So I will close this as off topic for this repository.

If you would like to learn how to write such code in a manner that will support the MKR WiFi 1010, you can study the library's "ArduinoIoTCloud-Basic" example sketch. If you would like assistance, please post over on Arduino Forum:

https://forum.arduino.cc/

I'm sure we'll be able to help you out over there.

**Comment by pennam** [comment] 2024-01-31 09:30
@per1234 I think @zfields is right. There is an issue with the examples includes, should be fixed by #412

**Comment by zfields** [comment] 2024-01-31 14:18
> If you would like to learn how to write such code in a manner that will support the MKR WiFi 1010, you can study the library's "ArduinoIoTCloud-Basic" example sketch.

If you study the error message, you can see that I tried to compile the `ArduinoIoTCloud_Basic` sketch, which resulted in this error.

**Comment by per1234** [comment] 2024-01-31 22:44
I see. The bug can only be reproduced when using the "old" Arduino Web Editor.

I was unable to reproduce it because I was using the "new" Cloud Editor, which does not currently automatically migrate [secrets](https://docs.arduino.cc/arduino-cloud/cloud-editor/store-your-sensitive-data-safely-when-sharing) when you open a sketch as the "old" editor does.

**Closed** 2024-02-19 11:16 UTC
Labels: type: imperfection, topic: code
