### ISSUE TITLE
`-Wvla` compiler warnings

### ISSUE THREAD

**Issue by zfields** [arduino-libraries/ArduinoIoTCloud#491] opened 2024-07-18 15:31 UTC
```
~/Development/Arduino/libraries/Arduino_DebugUtils/src/Arduino_DebugUtils.cpp: In member function 'void Arduino_DebugUtils::vPrint(const char*, va_list)':
~/Development/Arduino/libraries/Arduino_DebugUtils/src/Arduino_DebugUtils.cpp:139:28: warning: variable length array 'msg_buf' is used [-Wvla]
   char msg_buf[msg_buf_size];
                            ^
```

**Comment by zfields** [comment] 2024-07-18 19:48
```arduino-cli compile --verbose --warnings=all --build-property "build.extra_flags=-Wno-unused-variable -Wno-implicit-fallthrough -Wno-psabi -Wno-deprecated-copy -Wno-missing-field-initializers -Wno-delete-non-virtual-dtor -Wno-sign-compare -Og -g" --fqbn arduino:mbed_opta:opta <dev folder>```

**Comment by per1234** [comment] 2024-07-19 01:27
Thanks for taking the time to submit an issue @zfields.

I see you have also reported this in the issue tracker for the "DebugUtils" library: https://github.com/arduino-libraries/Arduino_DebugUtils/issues/44.

Since the warning is not caused by anything in the codebase of the "ArduinoIoTCloud" library, I will close this as off topic.

**Closed by per1234** 2024-07-19 01:27 UTC
Labels: type: imperfection

**Comment by zfields** [comment] 2024-07-19 11:20
Ah, yes, you are correct, this was a mispost.

Thank you for your patience. :pray:
