### ISSUE TITLE
Not Working with RBDIMMER 

### ISSUE THREAD

**Issue by jamsyogendra** [arduino-libraries/ArduinoIoTCloud#321] opened 2022-06-30 16:00 UTC
Hello everyone I am trying to add Rbdimmer in my project but i got an error can someone told me why this happens,

error while compile:

```
Arduino: 1.8.19 (Windows 10), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

WARNING: library ArduinoIoTCloud claims to run on mbed, samd, esp8266, mbed_nano, mbed_portenta, mbed_nicla architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).

In file included from C:\Users\jamsa\OneDrive\Desktop\Untitled_aug02a\Untitled_aug02a.ino:4:0:

C:\Users\jamsa\OneDrive\Documents\Arduino\libraries\RBDDimmer-master\src/RBDdimmer.h:32:11: error: 'OFF' redeclared as different kind of symbol

     OFF = false,

           ^

In file included from C:\Users\jamsa\OneDrive\Documents\Arduino\libraries\ArduinoIoTCloud\src/ArduinoIoTCloud.h:33:0,

                 from C:\Users\jamsa\OneDrive\Desktop\Untitled_aug02a\thingProperties.h:3,

                 from C:\Users\jamsa\OneDrive\Desktop\Untitled_aug02a\Untitled_aug02a.ino:2:

C:\Users\jamsa\OneDrive\Documents\Arduino\libraries\ArduinoIoTCloud\src/AIoTC_Const.h:26:19: note: previous declaration 'const bool OFF'

 static bool const OFF = false;

                   ^

In file included from C:\Users\jamsa\OneDrive\Desktop\Untitled_aug02a\Untitled_aug02a.ino:4:0:

C:\Users\jamsa\OneDrive\Documents\Arduino\libraries\RBDDimmer-master\src/RBDdimmer.h:33:10: error: 'ON' redeclared as different kind of symbol

     ON = true

          ^

In file included from C:\Users\jamsa\OneDrive\Documents\Arduino\libraries\ArduinoIoTCloud\src/ArduinoIoTCloud.h:33:0,

                 from C:\Users\jamsa\OneDrive\Desktop\Untitled_aug02a\thingProperties.h:3,

                 from C:\Users\jamsa\OneDrive\Desktop\Untitled_aug02a\Untitled_aug02a.ino:2:

C:\Users\jamsa\OneDrive\Documents\Arduino\libraries\ArduinoIoTCloud\src/AIoTC_Const.h:25:19: note: previous declaration 'const bool ON'

 static bool const ON  = true;

                   ^

C:\Users\jamsa\OneDrive\Desktop\Untitled_aug02a\Untitled_aug02a.ino: In function 'void setup()':

Untitled_aug02a:74:31: error: no matching function for call to 'dimmerLamp::begin(DIMMER_MODE_typedef, const bool&)'

   dimmer.begin(NORMAL_MODE, ON);

                               ^

In file included from C:\Users\jamsa\OneDrive\Desktop\Untitled_aug02a\Untitled_aug02a.ino:4:0:

C:\Users\jamsa\OneDrive\Documents\Arduino\libraries\RBDDimmer-master\src/RBDdimmer.h:63:14: note: candidate: void dimmerLamp::begin(DIMMER_MODE_typedef, ON_OFF_typedef)

         void begin(DIMMER_MODE_typedef DIMMER_MODE, ON_OFF_typedef ON_OFF);

              ^

C:\Users\jamsa\OneDrive\Documents\Arduino\libraries\RBDDimmer-master\src/RBDdimmer.h:63:14: note:   no known conversion for argument 2 from 'const bool' to 'ON_OFF_typedef'

Multiple libraries were found for "WiFi.h"

 Used: C:\Users\jamsa\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi

 Not used: C:\Users\jamsa\OneDrive\Documents\Arduino\libraries\WiFiNINA

 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi

exit status 1

no matching function for call to 'dimmerLamp::begin(DIMMER_MODE_typedef, const bool&)'



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```
**Any idea what is happing here**

**Comment by per1234** [comment] 2022-07-01 02:51
Duplicate of https://github.com/arduino-libraries/ArduinoIoTCloud/issues/280

**Closed by per1234** 2022-07-01 02:51 UTC
